cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - "packages/*"
  - "apps/*"

catalog:
  react: ^19.2.0
  react-dom: ^19.2.0
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3

  "@tanstack/react-router": ^1.162.4
  "@tanstack/react-start": ^1.162.4
  "@tanstack/router-plugin": ^1.162.4
  "@tanstack/react-router-devtools": ^1.162.4
  "@tanstack/react-router-ssr-query": ^1.162.4
  "@tanstack/react-devtools": ^0.9.6
  "@tanstack/devtools-vite": ^0.5.1

  tailwindcss: ^4.2.1
  "@tailwindcss/vite": ^4.2.1
